# Generated by Django 3.2.5 on 2023-11-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_appartment_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='appartment',
            name='bathrooms',
            field=models.CharField(default='self-contained', max_length=50),
        ),
    ]
