# Generated by Django 3.2.5 on 2024-01-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0004_appartment_bathrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appartment',
            old_name='rent_amount',
            new_name='rent_amount_maximum',
        ),
        migrations.AddField(
            model_name='appartment',
            name='care_taker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appartment',
            name='coordinates',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appartment',
            name='rent_amount_minimum',
            field=models.IntegerField(null=True),
        ),
    ]
